env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
plugins:
  - jest
  - prettier
extends: 
  - eslint:recommended 
  - plugin:jest/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
